Integrate MARS6 to bud-e
LAION-AI/bud-e pull request #1
Opened 2024-12-12 15:31 UTC by AZCamb

2024-12-20 09:59 UTC, akshhack requested changes

2024-12-20 09:59 UTC, akshhack commented on routes/api/tts.ts
> +    while (true) {
not good style. please use proper async pause loops....

2024-12-20 09:59 UTC, akshhack commented on routes/api/tts.ts
> +    if (ttsModel !== "MARS6") {
this looks ugly, cannot there be a switch statement or equivalent?

2025-01-10 21:18 UTC, robvanvolt commented
After fixing two bugs, i still get this only and no speech:

`Status code for creating TTS: 200
Polling: undefined
Polling: undefined
Polling: undefined
Polling: undefined`

The bugs were:

`    switch (useThisTtsModel) {`
    
    now instead of 
    
`        switch (useThisTtsKey) {`
        
  and
  
  
`  ttsKey, ttsKey `

was referenced twice instead of ttsUrl for the first parameter once (was an invalid URL).

2025-01-10 21:37 UTC, AZCamb commented on routes/api/tts.ts
> +          "x-api-header": ttsKey,
@robvanvolt This is the problematic code, causing the polling to return `undefined`, it should be `x-api-key` instead of `x-api-header`

2025-01-11 09:25 UTC, merged